[project]
authors = [{name = "Peter Limkilde Svendsen", email = "pelis@kds.dk"}]
dependencies = []
name = "gldemtools2"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project.scripts]
process_tile = "gldemtools2.cli:main"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tool.pixi.pypi-dependencies]
gldemtools2 = { path = ".", editable = true }

[tool.pixi.tasks]
process_tile = "process_tile"

[tool.pixi.dependencies]
numpy = ">=2.4.3,<3"
scipy = ">=1.17.1,<2"
gdal = ">=3.12.3,<4"
python = ">=3.14.3,<3.15"
libgdal-pg = ">=3.12.3,<4"

[tool.pixi.feature.test.dependencies]
mypy = ">=1.20.1,<2"
ruff = ">=0.15.10,<0.16"
pytest = ">=9.0.3,<10"

[tool.pixi.feature.test.tasks]
test = "pytest"
typecheck = "mypy ."
format = "ruff check"

[tool.pixi.environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[[tool.mypy.overrides]]
# GDAL does not play ball with type checking
module = ["osgeo.*"]
ignore_missing_imports = true
