name: Test

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        runners: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v6
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.65.0
        cache: true
    - run: pixi run test -vv
